/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIaRouteImport } from './routes/api/ia'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiWorkflowarkStateRouteImport } from './routes/api/workflowark.state'

const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaRoute = ApiIaRouteImport.update({
  id: '/api/ia',
  path: '/api/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWorkflowarkStateRoute = ApiWorkflowarkStateRouteImport.update({
  id: '/api/workflowark/state',
  path: '/api/workflowark/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sistema'
    | '/app'
    | '/api/ia'
    | '/api/workflowark/state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/sistema' | '/app' | '/api/ia' | '/api/workflowark/state'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sistema'
    | '/_authenticated/app'
    | '/api/ia'
    | '/api/workflowark/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SistemaRoute: typeof SistemaRoute
  ApiIaRoute: typeof ApiIaRoute
  ApiWorkflowarkStateRoute: typeof ApiWorkflowarkStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia': {
      id: '/api/ia'
      path: '/api/ia'
      fullPath: '/api/ia'
      preLoaderRoute: typeof ApiIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/workflowark/state': {
      id: '/api/workflowark/state'
      path: '/api/workflowark/state'
      fullPath: '/api/workflowark/state'
      preLoaderRoute: typeof ApiWorkflowarkStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SistemaRoute: SistemaRoute,
  ApiIaRoute: ApiIaRoute,
  ApiWorkflowarkStateRoute: ApiWorkflowarkStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
