/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIaRouteImport } from './routes/api/ia'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiWorkflowarkStateRouteImport } from './routes/api/workflowark.state'
import { Route as ApiWorkflowarkSheetRouteImport } from './routes/api/workflowark.sheet'
import { Route as ApiWorkflowarkAiCheckRouteImport } from './routes/api/workflowark.ai-check'
import { Route as ApiWorkflowarkAgentsRunRouteImport } from './routes/api/workflowark.agents-run'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiWorkflowarkWhatsappWebhookRouteImport } from './routes/api/workflowark.whatsapp.webhook'
import { Route as ApiWorkflowarkWhatsappSendRouteImport } from './routes/api/workflowark.whatsapp.send'
import { Route as ApiWorkflowarkWhatsappQrRouteImport } from './routes/api/workflowark.whatsapp.qr'
import { Route as ApiWorkflowarkWhatsappWebhookSplatRouteImport } from './routes/api/workflowark.whatsapp.webhook.$'

const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaRoute = ApiIaRouteImport.update({
  id: '/api/ia',
  path: '/api/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWorkflowarkStateRoute = ApiWorkflowarkStateRouteImport.update({
  id: '/api/workflowark/state',
  path: '/api/workflowark/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkSheetRoute = ApiWorkflowarkSheetRouteImport.update({
  id: '/api/workflowark/sheet',
  path: '/api/workflowark/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkAiCheckRoute = ApiWorkflowarkAiCheckRouteImport.update({
  id: '/api/workflowark/ai-check',
  path: '/api/workflowark/ai-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkAgentsRunRoute = ApiWorkflowarkAgentsRunRouteImport.update({
  id: '/api/workflowark/agents-run',
  path: '/api/workflowark/agents-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkWhatsappWebhookRoute =
  ApiWorkflowarkWhatsappWebhookRouteImport.update({
    id: '/api/workflowark/whatsapp/webhook',
    path: '/api/workflowark/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappSendRoute =
  ApiWorkflowarkWhatsappSendRouteImport.update({
    id: '/api/workflowark/whatsapp/send',
    path: '/api/workflowark/whatsapp/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappQrRoute =
  ApiWorkflowarkWhatsappQrRouteImport.update({
    id: '/api/workflowark/whatsapp/qr',
    path: '/api/workflowark/whatsapp/qr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappWebhookSplatRoute =
  ApiWorkflowarkWhatsappWebhookSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiWorkflowarkWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sistema': typeof SistemaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sistema'
    | '/app'
    | '/api/ia'
    | '/api/auth/signup'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/sheet'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sistema'
    | '/app'
    | '/api/ia'
    | '/api/auth/signup'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/sheet'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sistema'
    | '/_authenticated/app'
    | '/api/ia'
    | '/api/auth/signup'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/sheet'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SistemaRoute: typeof SistemaRoute
  ApiIaRoute: typeof ApiIaRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiWorkflowarkAgentsRunRoute: typeof ApiWorkflowarkAgentsRunRoute
  ApiWorkflowarkAiCheckRoute: typeof ApiWorkflowarkAiCheckRoute
  ApiWorkflowarkSheetRoute: typeof ApiWorkflowarkSheetRoute
  ApiWorkflowarkStateRoute: typeof ApiWorkflowarkStateRoute
  ApiWorkflowarkWhatsappQrRoute: typeof ApiWorkflowarkWhatsappQrRoute
  ApiWorkflowarkWhatsappSendRoute: typeof ApiWorkflowarkWhatsappSendRoute
  ApiWorkflowarkWhatsappWebhookRoute: typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia': {
      id: '/api/ia'
      path: '/api/ia'
      fullPath: '/api/ia'
      preLoaderRoute: typeof ApiIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/workflowark/state': {
      id: '/api/workflowark/state'
      path: '/api/workflowark/state'
      fullPath: '/api/workflowark/state'
      preLoaderRoute: typeof ApiWorkflowarkStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/sheet': {
      id: '/api/workflowark/sheet'
      path: '/api/workflowark/sheet'
      fullPath: '/api/workflowark/sheet'
      preLoaderRoute: typeof ApiWorkflowarkSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/ai-check': {
      id: '/api/workflowark/ai-check'
      path: '/api/workflowark/ai-check'
      fullPath: '/api/workflowark/ai-check'
      preLoaderRoute: typeof ApiWorkflowarkAiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/agents-run': {
      id: '/api/workflowark/agents-run'
      path: '/api/workflowark/agents-run'
      fullPath: '/api/workflowark/agents-run'
      preLoaderRoute: typeof ApiWorkflowarkAgentsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/webhook': {
      id: '/api/workflowark/whatsapp/webhook'
      path: '/api/workflowark/whatsapp/webhook'
      fullPath: '/api/workflowark/whatsapp/webhook'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/send': {
      id: '/api/workflowark/whatsapp/send'
      path: '/api/workflowark/whatsapp/send'
      fullPath: '/api/workflowark/whatsapp/send'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/qr': {
      id: '/api/workflowark/whatsapp/qr'
      path: '/api/workflowark/whatsapp/qr'
      fullPath: '/api/workflowark/whatsapp/qr'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/webhook/$': {
      id: '/api/workflowark/whatsapp/webhook/$'
      path: '/$'
      fullPath: '/api/workflowark/whatsapp/webhook/$'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappWebhookSplatRouteImport
      parentRoute: typeof ApiWorkflowarkWhatsappWebhookRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiWorkflowarkWhatsappWebhookRouteChildren {
  ApiWorkflowarkWhatsappWebhookSplatRoute: typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}

const ApiWorkflowarkWhatsappWebhookRouteChildren: ApiWorkflowarkWhatsappWebhookRouteChildren =
  {
    ApiWorkflowarkWhatsappWebhookSplatRoute:
      ApiWorkflowarkWhatsappWebhookSplatRoute,
  }

const ApiWorkflowarkWhatsappWebhookRouteWithChildren =
  ApiWorkflowarkWhatsappWebhookRoute._addFileChildren(
    ApiWorkflowarkWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SistemaRoute: SistemaRoute,
  ApiIaRoute: ApiIaRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiWorkflowarkAgentsRunRoute: ApiWorkflowarkAgentsRunRoute,
  ApiWorkflowarkAiCheckRoute: ApiWorkflowarkAiCheckRoute,
  ApiWorkflowarkSheetRoute: ApiWorkflowarkSheetRoute,
  ApiWorkflowarkStateRoute: ApiWorkflowarkStateRoute,
  ApiWorkflowarkWhatsappQrRoute: ApiWorkflowarkWhatsappQrRoute,
  ApiWorkflowarkWhatsappSendRoute: ApiWorkflowarkWhatsappSendRoute,
  ApiWorkflowarkWhatsappWebhookRoute:
    ApiWorkflowarkWhatsappWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
