/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as PostagensRouteImport } from './routes/postagens'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprovarRouteImport } from './routes/aprovar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TccApresentacaoRouteImport } from './routes/tcc.apresentacao'
import { Route as ApiIaRouteImport } from './routes/api/ia'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiWorkflowarkStateRouteImport } from './routes/api/workflowark.state'
import { Route as ApiWorkflowarkSocialRunRouteImport } from './routes/api/workflowark.social-run'
import { Route as ApiWorkflowarkSheetRouteImport } from './routes/api/workflowark.sheet'
import { Route as ApiWorkflowarkPortalRouteImport } from './routes/api/workflowark.portal'
import { Route as ApiWorkflowarkApproveRouteImport } from './routes/api/workflowark.approve'
import { Route as ApiWorkflowarkAiCheckRouteImport } from './routes/api/workflowark.ai-check'
import { Route as ApiWorkflowarkAgentsRunRouteImport } from './routes/api/workflowark.agents-run'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google.callback'
import { Route as ApiGoogleAuthRouteImport } from './routes/api/google.auth'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiAuthSeedEvaluatorsRouteImport } from './routes/api/auth.seed-evaluators'
import { Route as ApiWorkflowarkWhatsappWebhookRouteImport } from './routes/api/workflowark.whatsapp.webhook'
import { Route as ApiWorkflowarkWhatsappSendRouteImport } from './routes/api/workflowark.whatsapp.send'
import { Route as ApiWorkflowarkWhatsappQrRouteImport } from './routes/api/workflowark.whatsapp.qr'
import { Route as ApiWorkflowarkWhatsappWebhookSplatRouteImport } from './routes/api/workflowark.whatsapp.webhook.$'

const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const PostagensRoute = PostagensRouteImport.update({
  id: '/postagens',
  path: '/postagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarRoute = AprovarRouteImport.update({
  id: '/aprovar',
  path: '/aprovar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TccApresentacaoRoute = TccApresentacaoRouteImport.update({
  id: '/tcc/apresentacao',
  path: '/tcc/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaRoute = ApiIaRouteImport.update({
  id: '/api/ia',
  path: '/api/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWorkflowarkStateRoute = ApiWorkflowarkStateRouteImport.update({
  id: '/api/workflowark/state',
  path: '/api/workflowark/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkSocialRunRoute = ApiWorkflowarkSocialRunRouteImport.update({
  id: '/api/workflowark/social-run',
  path: '/api/workflowark/social-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkSheetRoute = ApiWorkflowarkSheetRouteImport.update({
  id: '/api/workflowark/sheet',
  path: '/api/workflowark/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkPortalRoute = ApiWorkflowarkPortalRouteImport.update({
  id: '/api/workflowark/portal',
  path: '/api/workflowark/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkApproveRoute = ApiWorkflowarkApproveRouteImport.update({
  id: '/api/workflowark/approve',
  path: '/api/workflowark/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkAiCheckRoute = ApiWorkflowarkAiCheckRouteImport.update({
  id: '/api/workflowark/ai-check',
  path: '/api/workflowark/ai-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkAgentsRunRoute = ApiWorkflowarkAgentsRunRouteImport.update({
  id: '/api/workflowark/agents-run',
  path: '/api/workflowark/agents-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAuthRoute = ApiGoogleAuthRouteImport.update({
  id: '/api/google/auth',
  path: '/api/google/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSeedEvaluatorsRoute = ApiAuthSeedEvaluatorsRouteImport.update({
  id: '/api/auth/seed-evaluators',
  path: '/api/auth/seed-evaluators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowarkWhatsappWebhookRoute =
  ApiWorkflowarkWhatsappWebhookRouteImport.update({
    id: '/api/workflowark/whatsapp/webhook',
    path: '/api/workflowark/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappSendRoute =
  ApiWorkflowarkWhatsappSendRouteImport.update({
    id: '/api/workflowark/whatsapp/send',
    path: '/api/workflowark/whatsapp/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappQrRoute =
  ApiWorkflowarkWhatsappQrRouteImport.update({
    id: '/api/workflowark/whatsapp/qr',
    path: '/api/workflowark/whatsapp/qr',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowarkWhatsappWebhookSplatRoute =
  ApiWorkflowarkWhatsappWebhookSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ApiWorkflowarkWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovar': typeof AprovarRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/postagens': typeof PostagensRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/tcc/apresentacao': typeof TccApresentacaoRoute
  '/api/auth/seed-evaluators': typeof ApiAuthSeedEvaluatorsRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/approve': typeof ApiWorkflowarkApproveRoute
  '/api/workflowark/portal': typeof ApiWorkflowarkPortalRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/social-run': typeof ApiWorkflowarkSocialRunRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovar': typeof AprovarRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/postagens': typeof PostagensRoute
  '/sistema': typeof SistemaRoute
  '/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/tcc/apresentacao': typeof TccApresentacaoRoute
  '/api/auth/seed-evaluators': typeof ApiAuthSeedEvaluatorsRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/approve': typeof ApiWorkflowarkApproveRoute
  '/api/workflowark/portal': typeof ApiWorkflowarkPortalRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/social-run': typeof ApiWorkflowarkSocialRunRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aprovar': typeof AprovarRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/postagens': typeof PostagensRoute
  '/sistema': typeof SistemaRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/api/ia': typeof ApiIaRoute
  '/tcc/apresentacao': typeof TccApresentacaoRoute
  '/api/auth/seed-evaluators': typeof ApiAuthSeedEvaluatorsRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/workflowark/agents-run': typeof ApiWorkflowarkAgentsRunRoute
  '/api/workflowark/ai-check': typeof ApiWorkflowarkAiCheckRoute
  '/api/workflowark/approve': typeof ApiWorkflowarkApproveRoute
  '/api/workflowark/portal': typeof ApiWorkflowarkPortalRoute
  '/api/workflowark/sheet': typeof ApiWorkflowarkSheetRoute
  '/api/workflowark/social-run': typeof ApiWorkflowarkSocialRunRoute
  '/api/workflowark/state': typeof ApiWorkflowarkStateRoute
  '/api/workflowark/whatsapp/qr': typeof ApiWorkflowarkWhatsappQrRoute
  '/api/workflowark/whatsapp/send': typeof ApiWorkflowarkWhatsappSendRoute
  '/api/workflowark/whatsapp/webhook': typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
  '/api/workflowark/whatsapp/webhook/$': typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovar'
    | '/auth'
    | '/portal'
    | '/postagens'
    | '/sistema'
    | '/app'
    | '/api/ia'
    | '/tcc/apresentacao'
    | '/api/auth/seed-evaluators'
    | '/api/auth/signup'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/approve'
    | '/api/workflowark/portal'
    | '/api/workflowark/sheet'
    | '/api/workflowark/social-run'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovar'
    | '/auth'
    | '/portal'
    | '/postagens'
    | '/sistema'
    | '/app'
    | '/api/ia'
    | '/tcc/apresentacao'
    | '/api/auth/seed-evaluators'
    | '/api/auth/signup'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/approve'
    | '/api/workflowark/portal'
    | '/api/workflowark/sheet'
    | '/api/workflowark/social-run'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aprovar'
    | '/auth'
    | '/portal'
    | '/postagens'
    | '/sistema'
    | '/_authenticated/app'
    | '/api/ia'
    | '/tcc/apresentacao'
    | '/api/auth/seed-evaluators'
    | '/api/auth/signup'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/workflowark/agents-run'
    | '/api/workflowark/ai-check'
    | '/api/workflowark/approve'
    | '/api/workflowark/portal'
    | '/api/workflowark/sheet'
    | '/api/workflowark/social-run'
    | '/api/workflowark/state'
    | '/api/workflowark/whatsapp/qr'
    | '/api/workflowark/whatsapp/send'
    | '/api/workflowark/whatsapp/webhook'
    | '/api/workflowark/whatsapp/webhook/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AprovarRoute: typeof AprovarRoute
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
  PostagensRoute: typeof PostagensRoute
  SistemaRoute: typeof SistemaRoute
  ApiIaRoute: typeof ApiIaRoute
  TccApresentacaoRoute: typeof TccApresentacaoRoute
  ApiAuthSeedEvaluatorsRoute: typeof ApiAuthSeedEvaluatorsRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiGoogleAuthRoute: typeof ApiGoogleAuthRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiWorkflowarkAgentsRunRoute: typeof ApiWorkflowarkAgentsRunRoute
  ApiWorkflowarkAiCheckRoute: typeof ApiWorkflowarkAiCheckRoute
  ApiWorkflowarkApproveRoute: typeof ApiWorkflowarkApproveRoute
  ApiWorkflowarkPortalRoute: typeof ApiWorkflowarkPortalRoute
  ApiWorkflowarkSheetRoute: typeof ApiWorkflowarkSheetRoute
  ApiWorkflowarkSocialRunRoute: typeof ApiWorkflowarkSocialRunRoute
  ApiWorkflowarkStateRoute: typeof ApiWorkflowarkStateRoute
  ApiWorkflowarkWhatsappQrRoute: typeof ApiWorkflowarkWhatsappQrRoute
  ApiWorkflowarkWhatsappSendRoute: typeof ApiWorkflowarkWhatsappSendRoute
  ApiWorkflowarkWhatsappWebhookRoute: typeof ApiWorkflowarkWhatsappWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postagens': {
      id: '/postagens'
      path: '/postagens'
      fullPath: '/postagens'
      preLoaderRoute: typeof PostagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar': {
      id: '/aprovar'
      path: '/aprovar'
      fullPath: '/aprovar'
      preLoaderRoute: typeof AprovarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcc/apresentacao': {
      id: '/tcc/apresentacao'
      path: '/tcc/apresentacao'
      fullPath: '/tcc/apresentacao'
      preLoaderRoute: typeof TccApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia': {
      id: '/api/ia'
      path: '/api/ia'
      fullPath: '/api/ia'
      preLoaderRoute: typeof ApiIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/workflowark/state': {
      id: '/api/workflowark/state'
      path: '/api/workflowark/state'
      fullPath: '/api/workflowark/state'
      preLoaderRoute: typeof ApiWorkflowarkStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/social-run': {
      id: '/api/workflowark/social-run'
      path: '/api/workflowark/social-run'
      fullPath: '/api/workflowark/social-run'
      preLoaderRoute: typeof ApiWorkflowarkSocialRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/sheet': {
      id: '/api/workflowark/sheet'
      path: '/api/workflowark/sheet'
      fullPath: '/api/workflowark/sheet'
      preLoaderRoute: typeof ApiWorkflowarkSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/portal': {
      id: '/api/workflowark/portal'
      path: '/api/workflowark/portal'
      fullPath: '/api/workflowark/portal'
      preLoaderRoute: typeof ApiWorkflowarkPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/approve': {
      id: '/api/workflowark/approve'
      path: '/api/workflowark/approve'
      fullPath: '/api/workflowark/approve'
      preLoaderRoute: typeof ApiWorkflowarkApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/ai-check': {
      id: '/api/workflowark/ai-check'
      path: '/api/workflowark/ai-check'
      fullPath: '/api/workflowark/ai-check'
      preLoaderRoute: typeof ApiWorkflowarkAiCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/agents-run': {
      id: '/api/workflowark/agents-run'
      path: '/api/workflowark/agents-run'
      fullPath: '/api/workflowark/agents-run'
      preLoaderRoute: typeof ApiWorkflowarkAgentsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/auth': {
      id: '/api/google/auth'
      path: '/api/google/auth'
      fullPath: '/api/google/auth'
      preLoaderRoute: typeof ApiGoogleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/seed-evaluators': {
      id: '/api/auth/seed-evaluators'
      path: '/api/auth/seed-evaluators'
      fullPath: '/api/auth/seed-evaluators'
      preLoaderRoute: typeof ApiAuthSeedEvaluatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/webhook': {
      id: '/api/workflowark/whatsapp/webhook'
      path: '/api/workflowark/whatsapp/webhook'
      fullPath: '/api/workflowark/whatsapp/webhook'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/send': {
      id: '/api/workflowark/whatsapp/send'
      path: '/api/workflowark/whatsapp/send'
      fullPath: '/api/workflowark/whatsapp/send'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/qr': {
      id: '/api/workflowark/whatsapp/qr'
      path: '/api/workflowark/whatsapp/qr'
      fullPath: '/api/workflowark/whatsapp/qr'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflowark/whatsapp/webhook/$': {
      id: '/api/workflowark/whatsapp/webhook/$'
      path: '/$'
      fullPath: '/api/workflowark/whatsapp/webhook/$'
      preLoaderRoute: typeof ApiWorkflowarkWhatsappWebhookSplatRouteImport
      parentRoute: typeof ApiWorkflowarkWhatsappWebhookRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiWorkflowarkWhatsappWebhookRouteChildren {
  ApiWorkflowarkWhatsappWebhookSplatRoute: typeof ApiWorkflowarkWhatsappWebhookSplatRoute
}

const ApiWorkflowarkWhatsappWebhookRouteChildren: ApiWorkflowarkWhatsappWebhookRouteChildren =
  {
    ApiWorkflowarkWhatsappWebhookSplatRoute:
      ApiWorkflowarkWhatsappWebhookSplatRoute,
  }

const ApiWorkflowarkWhatsappWebhookRouteWithChildren =
  ApiWorkflowarkWhatsappWebhookRoute._addFileChildren(
    ApiWorkflowarkWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AprovarRoute: AprovarRoute,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
  PostagensRoute: PostagensRoute,
  SistemaRoute: SistemaRoute,
  ApiIaRoute: ApiIaRoute,
  TccApresentacaoRoute: TccApresentacaoRoute,
  ApiAuthSeedEvaluatorsRoute: ApiAuthSeedEvaluatorsRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiGoogleAuthRoute: ApiGoogleAuthRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiWorkflowarkAgentsRunRoute: ApiWorkflowarkAgentsRunRoute,
  ApiWorkflowarkAiCheckRoute: ApiWorkflowarkAiCheckRoute,
  ApiWorkflowarkApproveRoute: ApiWorkflowarkApproveRoute,
  ApiWorkflowarkPortalRoute: ApiWorkflowarkPortalRoute,
  ApiWorkflowarkSheetRoute: ApiWorkflowarkSheetRoute,
  ApiWorkflowarkSocialRunRoute: ApiWorkflowarkSocialRunRoute,
  ApiWorkflowarkStateRoute: ApiWorkflowarkStateRoute,
  ApiWorkflowarkWhatsappQrRoute: ApiWorkflowarkWhatsappQrRoute,
  ApiWorkflowarkWhatsappSendRoute: ApiWorkflowarkWhatsappSendRoute,
  ApiWorkflowarkWhatsappWebhookRoute:
    ApiWorkflowarkWhatsappWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
